In [1]:
import pandas as pd

# 1. Plantenkenmerken DataFrame
planten_data = {
    "Plant": ["Lavendel", "Hortensia", "Buxus", "Klimop", "Rozemarijn", "Tomaat", "Vingerhoedskruid", "Salie", "Blauwe regen"],
    "Soortgroep": ["Sierplant", "Sierplant", "Haagplant", "Bodembedekker", "Kruiden", "Groente", "Sierplant", "Kruiden", "Klimplant"],
    "Inheems": ["Ja", "Nee", "Ja", "Ja", "Ja", "Nee", "Ja", "Ja", "Nee"],
    "Seizoensbestendig": ["Ja", "Ja", "Ja", "Ja", "Nee", "Nee", "Ja", "Ja", "Nee"],
    "Gevoelig voor": ["Natte grond, strenge vrost", "Felle zon, droogte", "Schimmels, droogte", "None", "Vrost, natte keligrond", "Vrost, wind, schaduw", "Natte grond, kalkrijke bodem", "Te natte grond", "Vorst, arme zandgrond"],
    "Aandacht": ["Laag", "Middel", "Hoog", "Laag", "Laag", "Hoog", "Middel", "Laag", "Middel"],
    "Temperatuur (°C)": ["10–30", "5–25", "-5–25", "-10–25", "10–35", "15–30", "5–25", "10–30", "10–25"],
    "Bodemtype": ["Zand, kalkrijk", "Voedselrijk", "Lichte klei", "Neutraal", "Droog, zanderig", "Humusrijk", "Zand/leem", "Goed drainerend", "Kalkrijk"],
    "Omgeving": ["Zon", "Halfzon", "Zon / schaduw", "Schaduwrijke muur", "Volle zon", "Kas, volle zon", "Halfzon", "Zon", "Zon"],
    "pH voorkeur": ["6–8", "5–6.5", "6–7", "5.5–7", "6–8", "6–6.8", "5.5–6.5", "6–7.5", "6–7"],
    "Windbestendig": ["Ja", "Nee", "Ja", "Ja", "Nee", "Nee", "Nee", "Ja", "Ja"],
    "Groeiwijze": ["Struikvormig", "Bossig", "Compact struik", "Klimplant", "Struik", "Staand / steun", "Staand", "Bossig", "Klimplant"],
    "Biodiversiteit": ["Hoog", "Gemiddeld", "Laag", "Hoog", "Gemiddeld", "Hoog", "Hoog", "Gemiddeld", "Gemiddeld"],
    "Schaduw": ["Nee", "Ja", "Ja", "Ja", "Nee", "Nee", "Ja", "Nee", "Nee"],
    "Geur": ["Ja", "Nee", "Nee", "Nee", "Ja", "Nee", "Ja", "Ja", "Ja"],
    "Ziektelast": ["Laag", "Gemiddeld", "Hoog", "Laag", "Laag", "Hoog", "Middel", "Laag", "Middel"],
    "Voorkomen": [4, 3, 2, 1, 5, 2, 4, 3, 1]
}
planten_df = pd.DataFrame(planten_data)

# 2. Gebruikerstuin-profiel
gebruikers_data = {
    "Gebruiker_ID": ["001", "002", "003", "004", "005"],
    "Naam": ["Jan", "Piet", "Klaas", "Marie", "Sophie"],
    "Provincie": ["Zuid-Holland", "Groningen", "Utrecht", "Noord-Brabant", "Limburg"],
    "Bodemtype": ["Zand", "Klei", "Leem", "Klei", "Kalkrijk"],
    "pH_Waarde": [6.3, 7.2, 6.8, 6.0, 7.5],
    "Zonuren_lente": [5, 4, 7, 6, 5],
    "Zonuren_zomer": [8, 6, 10, 9, 8],
    "Zonuren_herfst": [4, 3, 6, 5, 4],
    "Zonuren_winter": [2, 1, 3, 2, 2],
    "Tuin_m2": [50, 150, 80, 120, 100],
    "Windgevoelig": ["Ja", "Nee", "Ja", "Ja", "Nee"],
    "Schaduw_%": [20, 40, 60, 70, 15],
    "Huisdieren": ["Ja", "Nee", "Ja", "Nee", "Ja"],
    "Kinderen": ["Nee", "Ja", "Ja", "Nee", "Ja"],
    "Tuinstijl": ["Natuurlijk", "Speelvriendelijk", "Eetbaar/modern", "Klassiek", "Mediterraans"],
    "Onderhoudsniveau": ["Laag", "Gemiddeld", "Hoog", "Gemiddeld", "Laag"],
    "Allergieën": ["Geen", "Hooikoorts", "Geen", "Pollenallergie", "Geen"],
    "Budget": ["Midden", "Laag", "Hoog", "Laag", "Midden"]
}
gebruikers_df = pd.DataFrame(gebruikers_data)

# 3. Tuincentrum- en Beschikbaarheidsdata
winkel_data = {
    "Plant": ["Lavendel", "Hortensia", "Buxus", "Rozemarijn", "Tomaat", "Salie"],
    "Winkel": ["Tuinland", "Intratuin", "GroenRijk", "Tuinland", "De Boet", "GroenRijk"],
    "Beschikbaar": ["Ja", "Nee", "Ja", "Ja", "Ja", "Ja"],
    "Pot": ["Ja", "Nee", "Ja", "Ja", "Nee", "Ja"],
    "Prijs (EUR)": [4.95, 8.99, 12.50, 3.95, 2.50, 3.25],
    "Aanbieding": ["Ja", "Nee", "Ja", "Ja", "Nee", "Nee"]
}
tuinwinkel_df = pd.DataFrame(winkel_data)

# 4. Gebruikersvoorkeuren
voorkeuren_data = {
    "Gebruiker_ID": ["001", "002", "003", "004", "005"],
    "Geur": ["Ja", "Nee", "Ja", "Nee", "Ja"],
    "Bloemen": ["Ja", "Ja", "Ja", "Nee", "Ja"],
    "Eetbaar": ["Nee", "Ja", "Ja", "Nee", "Ja"],
    "Lage zorg": ["Ja", "Nee", "Nee", "Ja", "Ja"],
    "Kleur": ["Ja", "Nee", "Ja", "Nee", "Ja"],
    "Biodiversiteit": ["Ja", "Nee", "Ja", "Nee", "Ja"],
    "Klimplanten": ["Nee", "Ja", "Ja", "Nee", "Nee"],
    "Geen stekels": ["Ja", "Nee", "Ja", "Ja", "Ja"],
    "Compact": ["Ja", "Nee", "Nee", "Ja", "Ja"]
}
voorkeuren_df = pd.DataFrame(voorkeuren_data)

# 5. Plantcombinaties
combi_data = {
    "Plant A": ["Lavendel", "Hortensia", "Tomaat", "Buxus", "Klimop", "Salie"],
    "Plant B": ["Rozemarijn", "Lavendel", "Basilicum", "Lavendel", "Vingerhoedskruid", "Tomaat"],
    "Compatibel": ["Ja", "Nee", "Ja", "Ja", "Ja", "Ja"],
    "Type": ["Mediterraans", "Water mismatch", "Companion plants", "Vorm & geur", "Biodiversiteit", "Eetbaar kruidentuin"],
    "Reden": [
        "Zelfde zon- en bodemvoorkeuren",
        "Lavendel droog, hortensia vochtig",
        "Basilicum houdt plagen bij tomaten weg",
        "Strakke vorm vs. geurige bloei",
        "Schaduwrijke combinatie met bloei",
        "Zelfde zon en verzorging"
    ]
}
combinaties_df = pd.DataFrame(combi_data)

___
___

In [2]:
planten_df

,Plant,Soortgroep,Inheems,Seizoensbestendig,Gevoelig voor,Aandacht,Temperatuur (°C),Bodemtype,Omgeving,pH voorkeur,Windbestendig,Groeiwijze,Biodiversiteit,Schaduw,Geur,Ziektelast,Voorkomen
0,Lavendel,Sierplant,Ja,Ja,"Natte grond, strenge vrost",Laag,10–30,"Zand, kalkrijk",Zon,6–8,Ja,Struikvormig,Hoog,Nee,Ja,Laag,4
1,Hortensia,Sierplant,Nee,Ja,"Felle zon, droogte",Middel,5–25,Voedselrijk,Halfzon,5–6.5,Nee,Bossig,Gemiddeld,Ja,Nee,Gemiddeld,3
2,Buxus,Haagplant,Ja,Ja,"Schimmels, droogte",Hoog,-5–25,Lichte klei,Zon / schaduw,6–7,Ja,Compact struik,Laag,Ja,Nee,Hoog,2
3,Klimop,Bodembedekker,Ja,Ja,None,Laag,-10–25,Neutraal,Schaduwrijke muur,5.5–7,Ja,Klimplant,Hoog,Ja,Nee,Laag,1
4,Rozemarijn,Kruiden,Ja,Nee,"Vrost, natte keligrond",Laag,10–35,"Droog, zanderig",Volle zon,6–8,Nee,Struik,Gemiddeld,Nee,Ja,Laag,5
5,Tomaat,Groente,Nee,Nee,"Vrost, wind, schaduw",Hoog,15–30,Humusrijk,"Kas, volle zon",6–6.8,Nee,Staand / steun,Hoog,Nee,Nee,Hoog,2
6,Vingerhoedskruid,Sierplant,Ja,Ja,"Natte grond, kalkrijke bodem",Middel,5–25,Zand/leem,Halfzon,5.5–6.5,Nee,Staand,Hoog,Ja,Ja,Middel,4
7,Salie,Kruiden,Ja,Ja,Te natte grond,Laag,10–30,Goed drainerend,Zon,6–7.5,Ja,Bossig,Gemiddeld,Nee,Ja,Laag,3
8,Blauwe regen,Klimplant,Nee,Nee,"Vorst, arme zandgrond",Middel,10–25,Kalkrijk,Zon,6–7,Ja,Klimplant,Gemiddeld,Nee,Ja,Middel,1

De planten_df is de data van de soort planten die zijn gehaald uit de afbeeldingen met hun eigenshappen.<br>
De data die je ziet betekenen als volg:
- Soortgroep => Groep waar de plant in valt
- Inheems => Is de plant wel of niet inheems
- Seizoenbestendig => Is de plant wel of niet seizoen geschikt (gaat het dood in een bepaald seizoen)
- Gevoelig voor => Is te zien waarvoor de plant gevoelig is
- Aandacht => Hoeveel aandacht een plant nodig zou hebben
- Temperatuur => De overlevings temperatuur van de plant
- Bodemtype => geschikte bodem voor de plant
- Omgeving => Omgeving waar de plant gezond zal groeien
- pH voorkeur => De planten een hebben een pH-waarde om goed te kunnen groeien
- Windbestendig => Kan de plant de wind aan
- Groeiqijze => De manier hoe zoe een plant groeit
- Biodiversiteit => Hoeveel invloed het het heeft op de biodiversiteit
- Schadum => De hoeveelheid schaduw zo een plant genereerd
- Geur => Straat de plant geuren uit
- Ziektelast => Hoe groot is de kans dat die plant ziek kan worden
- Voorkomen => Hoeveel keren een plant voorkomt in de df van de gebruiker
___

In [3]:
gebruikers_df

,Gebruiker_ID,Naam,Provincie,Bodemtype,pH_Waarde,Zonuren_lente,Zonuren_zomer,Zonuren_herfst,Zonuren_winter,Tuin_m2,Windgevoelig,Schaduw_%,Huisdieren,Kinderen,Tuinstijl,Onderhoudsniveau,Allergieën,Budget
0,001,Jan,Zuid-Holland,Zand,6.3,5,8,4,2,50,Ja,20,Ja,Nee,Natuurlijk,Laag,Geen,Midden
1,002,Piet,Groningen,Klei,7.2,4,6,3,1,150,Nee,40,Nee,Ja,Speelvriendelijk,Gemiddeld,Hooikoorts,Laag
2,003,Klaas,Utrecht,Leem,6.8,7,10,6,3,80,Ja,60,Ja,Ja,Eetbaar/modern,Hoog,Geen,Hoog
3,004,Marie,Noord-Brabant,Klei,6.0,6,9,5,2,120,Ja,70,Nee,Nee,Klassiek,Gemiddeld,Pollenallergie,Laag
4,005,Sophie,Limburg,Kalkrijk,7.5,5,8,4,2,100,Nee,15,Ja,Ja,Mediterraans,Laag,Geen,Midden

Gebruikers_df is de data set die data bevat met de tuingegevens van de gebruiker.<br>
De data betekent als volg:
- Provincie => Waar de gebruiker zich bevindt
- Bodemtype => Wat voor soort bodem de gebruiker heeft in zijn tuin
- pH waarde => De pH-waarde die in de bodem voorkomt
- Zonuren => De hoeveelheid uren de zon aanwezig in de tuin
- Tuin_m2 => Is de oppervlakte van de tuin
- Windgevoelig => Ja: Er is veel en harde wind aanwezig, Nee: Weinig en geen harde wind aanwezig
- Schaduw_% => Hoeveel schaduw aanwezig is in de tuin
- Huisdieren => Heeft de perseen wel of geen huisdieren
- Kinderen => Heeft de persoon wel of geen kinderen die in de tuin kunnen gaan
- Tuinstijl => De stijn van de tuin
- Onderhoudsniveau => Hoeveel tijd wordt gestopt in het onderhouden van die tuin
- Allergiën => Heeft de gebruiker wel of geen last van een soort allergie
- Budget => Hoeveel de gebruiker instaat is uit te geven om een tuin in te richten en te onderhouden
___

In [4]:
tuinwinkel_df

        Plant     Winkel Beschikbaar  Pot  Prijs (EUR) Aanbieding
0    Lavendel   Tuinland          Ja   Ja         4.95         Ja
1   Hortensia  Intratuin         Nee  Nee         8.99        Nee
2       Buxus  GroenRijk          Ja   Ja        12.50         Ja
3  Rozemarijn   Tuinland          Ja   Ja         3.95         Ja
4      Tomaat    De Boet          Ja  Nee         2.50        Nee
5       Salie  GroenRijk          Ja   Ja         3.25        Nee

Is een mogelijke optie om mensen te advieseren waar zij zouden kunnen gaan om de geschikte planten aan te schaffen voor hun tuin.
___

In [5]:
voorkeuren_df

,Gebruiker_ID,Geur,Bloemen,Eetbaar,Lage zorg,Kleur,Biodiversiteit,Klimplanten,Geen stekels,Compact
0,001,Ja,Ja,Nee,Ja,Ja,Ja,Nee,Ja,Ja
1,002,Nee,Ja,Ja,Nee,Nee,Nee,Ja,Nee,Nee
2,003,Ja,Ja,Ja,Nee,Ja,Ja,Ja,Ja,Nee
3,004,Nee,Nee,Nee,Ja,Nee,Nee,Nee,Ja,Ja
4,005,Ja,Ja,Ja,Ja,Ja,Ja,Nee,Ja,Ja

De Voorkeuren_df zijn de voorkeuren van de gebruiker wat die in zijn tuin zou willen hebben
___

In [6]:
combinaties_df

,Plant A,Plant B,Compatibel,Type,Reden
0,Lavendel,Rozemarijn,Ja,Mediterraans,Zelfde zon- en bodemvoorkeuren
1,Hortensia,Lavendel,Nee,Water mismatch,"Lavendel droog, hortensia vochtig"
2,Tomaat,Basilicum,Ja,Companion plants,Basilicum houdt plagen bij tomaten weg
3,Buxus,Lavendel,Ja,Vorm & geur,Strakke vorm vs. geurige bloei
4,Klimop,Vingerhoedskruid,Ja,Biodiversiteit,Schaduwrijke combinatie met bloei
5,Salie,Tomaat,Ja,Eetbaar kruidentuin,Zelfde zon en verzorging

Welke planten het best zijn voor combinatie om te voldoen aan de voorkeuren van de gebruiker
___

# **Wanneer de gebruiker zich aanmeld**

**Kolommen die de gebruiker moet invullen:**
- Voornaam
- Tussen voegsel
- Achternaam
- Provincie
- Bodemtype
- Tuin m2
- Coördinaten
# ___
**Alternatieven**

Tuin situatie:<br>
- Provincie
<br><br>

Voorkeur van de gebruiker:<br>
- Seizoenbestendig
- Aandacht
- Bodemtype
- Omgeving (hoeveelheid zon)
- Geur
- Ziektelast

In [9]:
import pandas as pd
import numpy as np
import tkinter as tk
from tkinter import ttk
import random
import geocoder  # Voor automatische locatiebepaling
from datetime import datetime  # Voor het bijhouden van het tijdstip

# Laad gebruikersdata met alleen de benodigde kolommen
def laad_gebruikers_data(bestand='gebruikers_data.csv'):
    try:
        df = pd.read_csv(bestand)
        # Zorg ervoor dat de 'Gebruiker_ID' kolom altijd aanwezig is
        if 'Gebruiker_ID' not in df.columns:
            df['Gebruiker_ID'] = np.nan  # Of een ander standaard ID als dat gewenst is
        # Zorg ervoor dat de 'Tijdstip' kolom aanwezig is
        if 'Tijdstip' not in df.columns:
            df['Tijdstip'] = np.nan  # Maak een lege 'Tijdstip' kolom aan als die er nog niet is
        # Filter de DataFrame om alleen de benodigde kolommen te behouden
        kolommen = ['Gebruiker_ID', 'Voornaam', 'Tussen voegsel', 'Achternaam', 'Provincie', 'Bodemtype', 'Tuin_m2', 'Coördinaten', 'Tijdstip']
        return df[kolommen] if all(kol in df.columns for kol in kolommen) else pd.DataFrame(columns=kolommen)
    except FileNotFoundError:
        # Als het bestand niet bestaat, maak een lege DataFrame met de vereiste kolommen
        return pd.DataFrame(columns=['Gebruiker_ID', 'Voornaam', 'Tussen voegsel', 'Achternaam', 'Provincie', 'Bodemtype', 'Tuin_m2', 'Coördinaten', 'Tijdstip'])


# Sla gebruikersdata op met alleen de benodigde kolommen
def sla_gebruikers_data_op(df, bestand='gebruikers_data.csv'):
    df.to_csv(bestand, index=False)

# Voeg nieuwe gebruiker toe of haal bestaande ID op
def voeg_nieuwe_gebruiker_toe(voornaam, tussenvoegsel, achternaam, gebruikers_df):
    bestaande = gebruikers_df[(
        gebruikers_df["Voornaam"].fillna('') == voornaam) & 
        (gebruikers_df["Tussen voegsel"].fillna('') == tussenvoegsel) & 
        (gebruikers_df["Achternaam"].fillna('') == achternaam)
    ]

    if not bestaande.empty:
        bestaande_id = bestaande.iloc[0]["Gebruiker_ID"]
        # Kijk of er al een Tijdstip is, anders voeg een nieuwe toe
        if pd.isna(bestaande.iloc[0]["Tijdstip"]):
            bestaande.iloc[0]["Tijdstip"] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    else:
        while True:
            nieuwe_id = str(random.randint(100000, 999999))
            if nieuwe_id not in gebruikers_df["Gebruiker_ID"].astype(str).values:
                break
        bestaande_id = nieuwe_id

    nieuwe_gebruiker = pd.Series({
        'Tijdstip': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'Gebruiker_ID': bestaande_id,
        'Voornaam': voornaam,
        'Tussen voegsel': tussenvoegsel,
        'Achternaam': achternaam,
        'Provincie': None,
        'Bodemtype': None,
        'Tuin_m2': None,
        'Coördinaten': None
    })

    return nieuwe_gebruiker, gebruikers_df

# Bepaal provincie via IP
def bepaal_provincie():
    try:
        g = geocoder.ip('me')
        provincie = g.state
        return provincie if provincie else "Onbekend"
    except Exception as e:
        print(f"⚠️ Fout bij bepalen provincie: {e}")
        return "Onbekend"

# Start de GUI
def start_gui():
    global gebruikers_df

    root = tk.Tk()
    root.title("Gebruikersvoorkeuren")

    entries = {}
    keuzes = {
        "Provincie": ["Zuid-Holland", "Groningen", "Utrecht", "Noord-Brabant", "Limburg"],
        "Bodemtype": ["Zand", "Klei", "Leem", "Kalkrijk"]
    }

    numeriek_invul = [
        "Tuin_m2"
    ]

    # Naamvelden
    tk.Label(root, text="Voornaam:").grid(row=0, column=0, sticky="w")
    voornaam_entry = tk.Entry(root)
    voornaam_entry.grid(row=0, column=1)

    tk.Label(root, text="Tussen voegsel:").grid(row=1, column=0, sticky="w")
    tussenvoegsel_entry = tk.Entry(root)
    tussenvoegsel_entry.grid(row=1, column=1)

    tk.Label(root, text="Achternaam:").grid(row=2, column=0, sticky="w")
    achternaam_entry = tk.Entry(root)
    achternaam_entry.grid(row=2, column=1)

    row = 3
    for kolom, opties in keuzes.items():
        tk.Label(root, text=kolom + ":").grid(row=row, column=0, sticky="w")
        cb = ttk.Combobox(root, values=opties, state="readonly")
        cb.grid(row=row, column=1)
        entries[kolom] = cb
        row += 1

    for kolom in numeriek_invul:
        tk.Label(root, text=kolom + ":").grid(row=row, column=0, sticky="w")
        entry = tk.Entry(root)
        entry.grid(row=row, column=1)
        entries[kolom] = entry
        row += 1

    # Automatisch provincie invullen
    provincie = bepaal_provincie()
    entries["Provincie"].set(provincie)

    def on_next():
        global gebruikers_df

        voornaam = voornaam_entry.get().strip()
        tussenvoegsel = tussenvoegsel_entry.get().strip()
        achternaam = achternaam_entry.get().strip()

        nieuwe_gebruiker, gebruikers_df_local = voeg_nieuwe_gebruiker_toe(
            voornaam, tussenvoegsel, achternaam, gebruikers_df)

        for kolom in keuzes:
            waarde = entries[kolom].get()
            if waarde:
                nieuwe_gebruiker[kolom] = waarde

        for kolom in numeriek_invul:
            invoer = entries[kolom].get()
            try:
                nieuwe_gebruiker[kolom] = float(invoer) if invoer else np.nan
            except ValueError:
                nieuwe_gebruiker[kolom] = np.nan

        # Voeg coördinaten toe aan deze gebruiker
        try:
            g = geocoder.ip('me')
            locatie = g.latlng
            nieuwe_gebruiker['Coördinaten'] = locatie if locatie else "Onbekend"
        except Exception as e:
            print(f"⚠️ Fout bij ophalen coördinaten: {e}")
            nieuwe_gebruiker['Coördinaten'] = "Onbekend"

        gebruikers_df_local = pd.concat([gebruikers_df_local, nieuwe_gebruiker.to_frame().T], ignore_index=True)

        # Update de globale gebruikers_df
        gebruikers_df = gebruikers_df_local
        sla_gebruikers_data_op(gebruikers_df)

        print("👍 Gebruiker succesvol toegevoegd.")
        
        # Sluit de GUI pas na het opslaan van de gegevens
        root.quit()
        root.destroy()

    tk.Button(root, text="Next", command=on_next).grid(row=row, column=0, columnspan=2, pady=10)
    root.mainloop()

# Hoofduitvoering
gebruikers_df = laad_gebruikers_data()
start_gui()

gebruikers_df

👍 Gebruiker succesvol toegevoegd.

,Gebruiker_ID,Voornaam,Tussen voegsel,Achternaam,Provincie,Bodemtype,Tuin_m2,Coördinaten,Tijdstip
0,832037,Sven,,Satimin,South Holland,Klei,34.0,"[51.9225, 4.4792]",2025-05-19 10:22:26

___
# **Verzamelen van weer data**

- api = https://openweathermap.org/api
- key = https://home.openweathermap.org/

**Kolommen automatisch aanpakken:**
- Temp
- Neerslag
- zonuren
- windsnelheden
- hitte index
- shaduw

In [8]:
# import requests

# def haal_weer_op(lat, lon, api_key):
#     url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"
#     try:
#         response = requests.get(url)
#         data = response.json()
#         if response.status_code == 200:
#             weer = {
#                 "temperatuur": data['main']['temp'],
#                 "gevoelstemperatuur": data['main']['feels_like'],
#                 "beschrijving": data['weather'][0]['description'],
#                 "wind": data['wind']['speed'],
#                 "locatie": data['name']
#             }
#             return weer
#         else:
#             print("⚠️ Fout bij ophalen weerdata:", data.get("message", "Onbekende fout"))
#             return None
#     except Exception as e:
#         print("❌ Fout:", e)
#         return None

# # Voorbeeldgebruik
# api_key = "b39d15a2d7439871db1cffe6088a0ab9"
# lat = 51.9225# Amsterdam
# lon = 4.4792
# weer_info = haal_weer_op(lat, lon, api_key)

# if weer_info:
#     print("🌤️ Weer op locatie:")
#     for k, v in weer_info.items():
#         print(f"{k.capitalize()}: {v}")

In [10]:
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from timezonefinder import TimezoneFinder
import pandas as pd
import numpy as np
from meteostat import Stations, Daily
from pvlib.location import Location
import ast

# ---------------------------
# 📍 Coördinaten splitsen uit kolom 'Coördinaten'
# ---------------------------
def splits_coordinaten(df):
    latitudes = []
    longitudes = []

    for coord in df['Coördinaten']:
        try:
            if isinstance(coord, str) and coord.startswith('['):
                coord = ast.literal_eval(coord)
            if isinstance(coord, (list, tuple)) and len(coord) == 2:
                latitudes.append(coord[0])
                longitudes.append(coord[1])
            else:
                latitudes.append(None)
                longitudes.append(None)
        except:
            latitudes.append(None)
            longitudes.append(None)

    df['Latitude'] = latitudes
    df['Longitude'] = longitudes
    return df

# Pas toe op je gebruikers-DataFrame
gebruikers_df = splits_coordinaten(gebruikers_df)

# 📍 Haal de coördinaten en gebruiker ID op uit de laatste rij
laatste_lat = gebruikers_df['Latitude'].iloc[-1]
laatste_lon = gebruikers_df['Longitude'].iloc[-1]
gebruikers_id = gebruikers_df['Gebruiker_ID'].iloc[-1]  # Pas aan als kolom anders heet

# 🌍 Zoek automatisch de tijdzone op
tf = TimezoneFinder()
plaatsnaam = tf.timezone_at(lat=laatste_lat, lng=laatste_lon)

# 🕒 Definieer start- en einddatum (start op 1e dag 3 jaar geleden)
end = datetime.now()
start = (end - relativedelta(years=3)).replace(day=1)

# 🌤️ Dagelijkse weerdata ophalen
station = Stations().nearby(laatste_lat, laatste_lon).fetch(1)
station_id = station.index[0]
data = Daily(station_id, start, end).fetch()

df_dag = data[['tavg', 'prcp', 'wspd']]
df_dag.index = pd.to_datetime(df_dag.index)

# 🌞 Zonhoogte per dag
locatie = Location(laatste_lat, laatste_lon, plaatsnaam)
zon_hoogtes = []
zonsopkomst_tijden = []
zonsondergang_tijden = []

for datum in df_dag.index:
    uren = pd.date_range(datum.strftime('%Y-%m-%d 00:00:00'), periods=24, freq='H', tz=plaatsnaam)
    zonne_positie = locatie.get_solarposition(uren)
    zonhoogte_dag = zonne_positie['apparent_elevation'].mean()
    zon_hoogtes.append(zonhoogte_dag)

    # Haal zonsopkomst en zonsondergang
    try:
        zonsopkomst = zonne_positie[zonne_positie['apparent_elevation'] > 0].index[0]
        zonsondergang = zonne_positie[zonne_positie['apparent_elevation'] > 0].index[-1]
        zonsopkomst_tijden.append(zonsopkomst.strftime('%H:%M'))
        zonsondergang_tijden.append(zonsondergang.strftime('%H:%M'))
    except IndexError:
        zonsopkomst_tijden.append("00:00")
        zonsondergang_tijden.append("00:00")

df_dag['zonhoogte (°)'] = zon_hoogtes
df_dag['zonsopkomst'] = zonsopkomst_tijden
df_dag['zonsondergang'] = zonsondergang_tijden

# 🥵 Hitte-index berekenen
def calculate_heat_index(temp_c):
    return temp_c * 1.8 + 32  # °C naar °F

df_dag['hitte_index (°F)'] = df_dag['tavg'].apply(calculate_heat_index).round(2)

# Kolommen hernoemen
df_dag = df_dag.rename(columns={
    'tavg': 'temp (°C)',
    'prcp': 'neerslag (mm)',
    'wspd': 'windsnelheid (m/s)',
})

# 🌤️ Daglengte berekenen in uren
df_dag['zonsondergang_dt'] = pd.to_datetime(df_dag['zonsondergang'], format='%H:%M', errors='coerce')
df_dag['zonsopkomst_dt'] = pd.to_datetime(df_dag['zonsopkomst'], format='%H:%M', errors='coerce')

df_dag['zonuren'] = (df_dag['zonsondergang_dt'] - df_dag['zonsopkomst_dt']).dt.total_seconds() / 3600

# Opschonen
df_dag = df_dag.drop(columns=['zonsondergang', 'zonsopkomst', 'zonsondergang_dt', 'zonsopkomst_dt'])
df_dag = df_dag.fillna(0)

# 📆 Maandgemiddelden berekenen
df_dag.index = pd.to_datetime(df_dag.index)
df_maand = df_dag.resample('M').mean().round(2)

# ➕ Gebruiker ID toevoegen en vooraan zetten
df_maand['Gebruiker_ID'] = gebruikers_id
cols = ['Gebruiker_ID'] + [c for c in df_maand.columns if c != 'Gebruiker_ID']
df_maand = df_maand[cols]

# Opslaan naar CSV met de naam ID van de gebruiker
df_maand.to_csv(f'{gebruikers_id}_maandgemiddelden.csv', index=True)

# ✅ Resultaat
df_maand

FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.

,Gebruiker_ID,temp (°C),neerslag (mm),windsnelheid (m/s),zonhoogte (°),hitte_index (°F),zonuren
time,,,,,,,
2022-05-31,832037,14.42,1.71,13.34,16.78,57.95,14.73
2022-06-30,832037,17.23,2.77,12.74,20.28,63.01,15.60
2022-07-31,832037,18.91,0.35,11.71,18.56,66.03,15.06
2022-08-31,832037,20.21,0.76,10.50,11.96,68.38,13.52
2022-09-30,832037,15.43,5.55,10.92,2.45,59.77,11.53
2022-10-31,832037,13.81,1.99,14.03,-7.78,56.86,9.58
2022-11-30,832037,9.03,4.05,17.43,-16.18,48.25,7.67
2022-12-31,832037,4.12,2.97,15.55,-20.12,39.42,7.00
2023-01-31,832037,6.06,4.79,20.51,-18.11,42.90,7.48
2023-02-28,832037,6.00,0.73,14.47,-11.21,42.79,8.86
2023-03-31,832037,7.07,3.62,18.49,-1.53,44.73,10.77
2023-04-30,832037,8.91,2.37,15.24,8.68,48.04,12.77
2023-05-31,832037,13.37,1.30,12.92,16.62,56.07,14.71
2023-06-30,832037,19.49,0.17,13.74,20.27,67.08,15.57
2023-07-31,832037,18.46,3.45,17.48,18.59,65.22,15.10
2023-08-31,832037,18.07,2.99,13.36,12.03,64.53,13.55
2023-09-30,832037,18.28,2.67,11.62,2.53,64.91,11.57
2023-10-31,832037,13.76,6.12,16.77,-7.71,56.78,9.61
2023-11-30,832037,8.49,6.01,19.96,-16.13,47.28,7.70
2023-12-31,832037,7.28,3.37,22.31,-20.11,45.10,7.00
2024-01-31,832037,4.32,2.88,19.24,-18.14,39.78,7.48
2024-02-29,832037,8.43,3.90,20.13,-11.12,47.18,8.90
2024-03-31,832037,9.02,1.30,15.71,-1.26,48.24,10.84
2024-04-30,832037,10.84,2.86,18.33,8.92,51.52,12.83
2024-05-31,832037,15.39,3.98,12.45,16.77,59.71,14.74
2024-06-30,832037,15.87,1.71,13.23,20.29,60.56,15.60
2024-07-31,832037,18.27,3.71,13.32,18.49,64.89,15.03
2024-08-31,832037,19.72,1.44,13.34,11.82,67.50,13.52
2024-09-30,832037,16.20,4.53,13.62,2.27,61.16,11.50
2024-10-31,832037,12.58,1.77,12.36,-7.95,54.65,9.55
2024-11-30,832037,7.62,3.05,13.55,-16.29,45.72,7.63
2024-12-31,832037,6.54,2.98,18.73,-20.14,43.77,7.00
2025-01-31,832037,3.96,2.86,14.98,-18.02,39.14,7.52
2025-02-28,832037,4.14,0.88,14.46,-11.05,39.46,8.89
2025-03-31,832037,7.47,0.21,10.93,-1.34,45.45,10.84
2025-04-30,832037,11.59,0.99,12.85,8.84,52.86,12.80
2025-05-31,832037,14.07,0.08,13.11,15.58,57.32,14.58

In [10]:
lat = gebruikers_df['Latitude'].iloc[-1]
lon = gebruikers_df['Longitude'].iloc[-1]

stations = Stations().nearby(lat, lon).fetch(10)
print(stations[['name', 'country', 'region', 'latitude', 'longitude']])

                                 name country region  latitude  longitude
id
06344  Rotterdam Airport Zestienhoven      NL     ZH   51.9500     4.4500
06343         Rotterdam Geulhaven Aws      NL     ZH   51.8833     4.3167
06330                Hoek Van Holland      NL     ZH   51.9833     4.1000
06210                      Valkenburg      NL     ZH   52.1833     4.4167
06348                    Cabauw Tower      NL     UT   51.9667     4.9333
06240      Amsterdam Airport Schiphol      NL     NH   52.3000     4.7667
06356                   Herwijnen Aws      NL     GE   51.8667     5.1500
06324                      Stavenisse      NL     ZE   51.5956     4.0061
06350                     Gilze-Rijen      NL     NB   51.5667     4.9333
06331                       Tholen Wp      NL     ZE   51.5167     4.1333

___
# **Voorkeuren van de gebruiker**

**Adviezen voor de tuin:**
- Huisdieren
- Kinderen (is niet relevant indien nodig)
- Tuinstijl
- Onderhoudsniveau
- Alergieën
- Budget

___
# **Gebruikers Maken + voorstellen**

In [11]:
import tkinter as tk
from tkinter import messagebox, ttk
import pandas as pd
import os
import random
from datetime import datetime
import geocoder

# Voeg nieuwe gebruiker toe of haal bestaande ID op
def genereer_gebruiker_id(voornaam, tussenvoegsel, achternaam, gebruikers_df):
    bestaande = gebruikers_df[
        (gebruikers_df["Voornaam"].fillna('').str.lower() == voornaam.lower()) &
        (gebruikers_df["Tussenvoegsel"].fillna('').str.lower() == tussenvoegsel.lower()) &
        (gebruikers_df["Achternaam"].fillna('').str.lower() == achternaam.lower())
    ]
    if not bestaande.empty:
        return bestaande.iloc[0]["Gebruiker_ID"]
    else:
        while True:
            nieuwe_id = str(random.randint(100000, 999999))
            if nieuwe_id not in gebruikers_df["Gebruiker_ID"].astype(str).values:
                return nieuwe_id

# Bepaal provincie en coördinaten via IP
def bepaal_locatie():
    try:
        g = geocoder.ip('me')
        provincie = g.state if g.state else "Onbekend"
        lat, lng = g.latlng if g.latlng else (None, None)
        return provincie, lat, lng
    except:
        return "Onbekend", None, None

# ---------- Tweede GUI ----------
def start_advies_gui(gebruikers_df):
    root = tk.Tk()
    root.title("Adviezen voor de tuin")

    opties = {
        "Huisdieren": ["Hond", "Kat", "Konijn", "Geen"],
        "Tuinstijl": ["Modern", "Klassiek", "Natuurlijk", "Onderhoudsvriendelijk"],
        "Onderhoudsniveau": ["Laag", "Gemiddeld", "Hoog"],
        "Allergieën": ["Pollen", "Bijengif", "Grassen", "Geen"]
    }

    entries = {}

    def maak_multiple_choice(row, label_text, opties_lijst):
        tk.Label(root, text=label_text + ":").grid(row=row, column=0, sticky="w", pady=2)
        vars_lijst = []
        for i, optie in enumerate(opties_lijst):
            var = tk.BooleanVar()
            chk = tk.Checkbutton(root, text=optie, variable=var)
            chk.grid(row=row+i, column=1, sticky="w")
            vars_lijst.append((optie, var))
        return row + len(opties_lijst), vars_lijst

    row = 0
    for label, keuzes in opties.items():
        row, var_lijst = maak_multiple_choice(row, label, keuzes)
        entries[label] = var_lijst

    # Budget label en entry
    tk.Label(root, text="Budget (€):").grid(row=row, column=0, sticky="w", pady=5)
    budget_entry = tk.Entry(root)
    budget_entry.grid(row=row, column=1, sticky="w", pady=5)
    row += 1

    def on_save():
        advies_dict = {}
        for label, var_lijst in entries.items():
            geselecteerd = [optie for optie, var in var_lijst if var.get()]
            advies_dict[label] = ', '.join(geselecteerd)

        budget = budget_entry.get().strip()
        try:
            advies_dict["Budget"] = float(budget) if budget else None
        except ValueError:
            messagebox.showerror("Fout", "Voer een geldig getal in voor het budget.")
            return

        for key, value in advies_dict.items():
            gebruikers_df.at[gebruikers_df.index[-1], key] = value

        gebruikers_df.to_csv("Geb_data.csv", index=False)
        print("✅ Adviesgegevens toegevoegd aan gebruiker:")
        print(gebruikers_df.tail(1))

        root.quit()
        root.destroy()

    tk.Button(root, text="Opslaan", command=on_save).grid(row=row, column=0, columnspan=2, pady=10)

    root.mainloop()

# ---------- Eerste GUI ----------
def start_gui():
    root = tk.Tk()
    root.title("Tuinadvies - Gebruikersgegevens")

    labels = ["Naam", "Geboortejaar", "Geslacht", "Ervaring met tuinieren (jaren)", "Soort woning"]
    entries = {}

    geslacht_opties = ["Man", "Vrouw", "Anders"]
    woning_opties = ["Appartement", "Tussenwoning", "Hoekwoning", "Vrijstaand"]

    # Naam
    tk.Label(root, text="Naam").grid(row=0, column=0, sticky="w", pady=3)
    naam_entry = tk.Entry(root)
    naam_entry.grid(row=0, column=1, sticky="w", pady=3)
    entries["Naam"] = naam_entry

    # Geboortejaar als Combobox dropdown met jaartallen
    tk.Label(root, text="Geboortejaar").grid(row=1, column=0, sticky="w", pady=3)
    huidig_jaar = datetime.now().year
    jaren = list(range(huidig_jaar, 1899, -1))
    geboortejaar_combo = ttk.Combobox(root, values=jaren, state="readonly")
    geboortejaar_combo.current(0)
    geboortejaar_combo.grid(row=1, column=1, sticky="w", pady=3)
    entries["Geboortejaar"] = geboortejaar_combo

    # Ervaring met tuinieren
    tk.Label(root, text="Ervaring met tuinieren (jaren)").grid(row=2, column=0, sticky="w", pady=3)
    ervaring_entry = tk.Entry(root)
    ervaring_entry.grid(row=2, column=1, sticky="w", pady=3)
    entries["Ervaring met tuinieren (jaren)"] = ervaring_entry

    # Geslacht met Radiobuttons
    tk.Label(root, text="Geslacht:").grid(row=3, column=0, sticky="w", pady=3)
    geslacht_var = tk.StringVar(value=geslacht_opties[0])
    for idx, optie in enumerate(geslacht_opties):
        tk.Radiobutton(root, text=optie, variable=geslacht_var, value=optie).grid(row=3, column=1+idx, sticky="w")

    # Soort woning met Radiobuttons
    tk.Label(root, text="Soort woning:").grid(row=4, column=0, sticky="w", pady=3)
    woning_var = tk.StringVar(value=woning_opties[0])
    for idx, optie in enumerate(woning_opties):
        tk.Radiobutton(root, text=optie, variable=woning_var, value=optie).grid(row=4, column=1+idx, sticky="w")

    def split_naam_volledig(naam):
        delen = naam.strip().split()
        if len(delen) == 0:
            return "", "", ""
        elif len(delen) == 1:
            return delen[0], "", ""
        elif len(delen) == 2:
            return delen[0], "", delen[1]
        else:
            return delen[0], " ".join(delen[1:-1]), delen[-1]

    def on_next():
        data = {}
        for label in ["Naam", "Geboortejaar", "Ervaring met tuinieren (jaren)"]:
            waarde = entries[label].get().strip()
            if not waarde:
                messagebox.showerror("Fout", f"Vul alle velden in (ontbreekt: {label})")
                return
            data[label] = waarde

        try:
            geboortejaar = int(data["Geboortejaar"])
            huidig_jaar = datetime.now().year
            leeftijd = huidig_jaar - geboortejaar
            if leeftijd < 0 or leeftijd > 120:
                messagebox.showerror("Fout", "Voer een geldig geboortejaar in.")
                return
            data["Leeftijd"] = leeftijd
            data["Ervaring met tuinieren (jaren)"] = int(data["Ervaring met tuinieren (jaren)"])
        except ValueError:
            messagebox.showerror("Fout", "Geboortejaar en ervaring moeten getallen zijn.")
            return

        del data["Geboortejaar"]

        data["Geslacht"] = geslacht_var.get()
        data["Soort woning"] = woning_var.get()

        voornaam, tussenvoegsel, achternaam = split_naam_volledig(data["Naam"])
        data["Voornaam"] = voornaam.lower()
        data["Tussenvoegsel"] = tussenvoegsel.lower()
        data["Achternaam"] = achternaam.lower()
        del data["Naam"]

        bestand = "Geb_data.csv"
        kolommen = ["Tijdstip", "Gebruiker_ID", "Voornaam", "Tussenvoegsel", "Achternaam", "Leeftijd",
                    "Geslacht", "Provincie", "Latitude", "Longitude",
                    "Ervaring met tuinieren (jaren)", "Soort woning",
                    "Tuinstijl", "Onderhoudsniveau", "Allergieën", "Huisdieren", "Budget"]

        if os.path.exists(bestand):
            gebruikers_df = pd.read_csv(bestand)
        else:
            gebruikers_df = pd.DataFrame(columns=kolommen)

        gebruiker_id = genereer_gebruiker_id(voornaam, tussenvoegsel, achternaam, gebruikers_df)
        provincie, lat, lng = bepaal_locatie()

        data["Gebruiker_ID"] = gebruiker_id
        data["Tijdstip"] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        data["Provincie"] = provincie
        data["Latitude"] = lat
        data["Longitude"] = lng

        for kolom in kolommen:
            if kolom not in data:
                data[kolom] = None

        gebruikers_df = pd.concat([gebruikers_df, pd.DataFrame([data])], ignore_index=True)
        gebruikers_df.to_csv(bestand, index=False)

        root.quit()
        root.destroy()

        start_advies_gui(gebruikers_df)

    tk.Button(root, text="Volgende", command=on_next).grid(row=5, column=0, columnspan=5, pady=10)

    root.mainloop()

# ---------- Start applicatie ----------
if __name__ == "__main__":
    start_gui()

✅ Adviesgegevens toegevoegd aan gebruiker:
              Tijdstip  Gebruiker_ID Voornaam Tussenvoegsel Achternaam  \
5  2025-05-19 10:23:19        249568     sven                  satimin

   Leeftijd Geslacht      Provincie  Latitude  Longitude  \
5        23      Man  South Holland   51.9225     4.4792

   Ervaring met tuinieren (jaren) Soort woning Tuinstijl Onderhoudsniveau  \
5                               5  Appartement    Modern             Laag

  Allergieën Huisdieren Budget
5     Pollen       Hond   None

In [12]:
df = pd.read_csv("Geb_data.csv")
df

,Tijdstip,Gebruiker_ID,Voornaam,Tussenvoegsel,Achternaam,Leeftijd,Geslacht,Provincie,Latitude,Longitude,Ervaring met tuinieren (jaren),Soort woning,Tuinstijl,Onderhoudsniveau,Allergieën,Huisdieren,Budget
0,2025-05-19 00:03:03,270206,SS,NaN,NaN,23,Man,South Holland,51.9225,4.4792,5,Appartement,Modern,Laag,Pollen,Hond,NaN
1,2025-05-19 00:05:08,270206,SS,NaN,NaN,23,Man,South Holland,51.9225,4.4792,5,Appartement,Klassiek,Gemiddeld,Bijengif,Konijn,NaN
2,2025-05-19 00:12:04,270206,SS,NaN,NaN,23,Man,South Holland,51.9225,4.4792,5,Appartement,NaN,NaN,NaN,NaN,NaN
3,2025-05-19 00:13:06,249568,Sven,NaN,Satimin,23,Man,South Holland,51.9225,4.4792,5,Appartement,NaN,NaN,NaN,NaN,NaN
4,2025-05-19 00:14:40,249568,sven,NaN,satimin,23,Man,South Holland,51.9225,4.4792,5,Appartement,NaN,NaN,NaN,NaN,NaN
5,2025-05-19 10:23:19,249568,sven,NaN,satimin,23,Man,South Holland,51.9225,4.4792,5,Appartement,Modern,Laag,Pollen,Hond,NaN

___
# **Connect met mobiel**

___
# **Dataframe voor prompting**

In [11]:
# Het inlezen van de CSV-bestanden met 'maandgemiddelden' als naam
def laad_maandgemiddelden(gebruikers_id):
    try:
        df = pd.read_csv(f'{gebruikers_id}_maandgemiddelden.csv')
        return df
    except FileNotFoundError:
        print("⚠️ Bestand niet gevonden.")
        return None

def laad_gebruikers_data(bestand='gebruikers_data.csv'):
    try:
        df = pd.read_csv(bestand)
        return df
    except FileNotFoundError:
        print("⚠️ Bestand niet gevonden.")
        return None

x = laad_maandgemiddelden(gebruikers_id)
x.columns

Index(['time', 'Gebruiker_ID', 'temp (°C)', 'neerslag (mm)',
       'windsnelheid (m/s)', 'zonhoogte (°)', 'hitte_index (°F)', 'zonuren'],
      dtype='object')

In [12]:
y = laad_gebruikers_data()
y.columns

Index(['Gebruiker_ID', 'Voornaam', 'Tussen voegsel', 'Achternaam', 'Provincie',
       'Bodemtype', 'Tuin_m2', 'Coördinaten', 'Tijdstip'],
      dtype='object')

___
## **Foto's dataframe**

Locate coordinates of user
probe 3 psx